---
title: "Employment and Education Opportunities in High Crime Cities"
author: "Andre Velez"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## __Focus__
_What correlation does crime have on unemployment and educational opportunities? What effect is there on the economic mobility of a citizen who lives in these areas?_ 


## __Clients__

__Government administration and legislature__

* Economic mobility has been shown to directly correlate to the strength of a first world economy

* Clients should use this data to direct policy and reallocate resources towards evidence-based strategies to reduce crime, facilitate continuing education, and generate jobs that could have a compound positive effect on the local community and economy.


## __Data Source__

__"U.S. Unemployment Rate by County, 1990-2016"__ _(U.S. Buearu of Labor Statistics)_ 

* https://www.kaggle.com/jayrav13/unemployment-by-county-us

__"FBI Uniform Crime Report"__ _(FBI)_

* https://ucr.fbi.gov/crime-in-the-u.s/2016/preliminary-semiannual-uniform-crime-report-januaryjune-2016

__"College Scorecard Data"__ _(U.S. Department of Education)_

* https://collegescorecard.ed.gov/data/


## __Solution__

* Explore crime data from the last 3 years in the FBI Uniform Crime Report for the top 3 violent cities and the top 3 safest cities in the U.S.

* Explore the last 3 years of the U.S. Unemployment Rate for the counties that correlate to the previous 6 cities

* Explore the College Scorecard Data present in the previous 6 counties

* Arrange the data in a uniform and managable format that combines all three data sets

* Utilize EDA to find any patterns and/or differences between the 6 cities and their data

* Determine solutions via evidence based data found to solve any discoverable patterns


## __Deliverables__

* Source Code.

* Report describing in detail the steps taken to find a solution to the hypothesis.

* Slide Deck to present the findings in a deliverable and actionable manner.